# Generated by Django 5.0.7 on 2024-09-20 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
        ('user', '0005_alter_customadmin_options_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='user.customuser'),
            preserve_default=False,
        ),
    ]
