# Generated by Django 5.0.7 on 2024-09-20 12:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='유저 아이디')),
                ('external_uuid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='통신용 uuid')),
                ('name', models.CharField(max_length=30, verbose_name='유저 이름')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='유저 이메일')),
                ('is_active', models.BooleanField(default=True, verbose_name='유저 사용 유무')),
                ('is_staff', models.BooleanField(default=False, verbose_name='유저 관리자 유무')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='생성 일자')),
            ],
            options={
                'db_table': 'user_user',
            },
        ),
        migrations.CreateModel(
            name='CustomAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='유저 아이디')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_time', models.DateTimeField(auto_now_add=True, verbose_name='수정 일시')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'user_django_admin',
            },
        ),
    ]
