# Generated by Django 5.0.7 on 2024-09-20 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customadmin_email_customadmin_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customadmin',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
