# Generated by Django 5.0.7 on 2024-09-20 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_customadmin_created_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customadmin',
            options={'verbose_name_plural': '장고 어드민 계정'},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name_plural': '유저 및 관리자 계정'},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='external_uuid',
        ),
        migrations.AlterField(
            model_name='customadmin',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True, verbose_name='이메일'),
        ),
        migrations.AlterField(
            model_name='customadmin',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='성'),
        ),
        migrations.AlterField(
            model_name='customadmin',
            name='is_staff',
            field=models.BooleanField(default=True, verbose_name='관리자 유무'),
        ),
        migrations.AlterField(
            model_name='customadmin',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='이름'),
        ),
    ]
